"""Photos: every file is CC0 or CC BY-SA from Wikimedia Commons, licence checked on the file page on 8 Oct 2026.
Source data: /workspace/animal-sites/big-cats/photos/chosen.json. Images are cropped to 3:2 and saved as WebP at 960 and 480 px wide."""
import html, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def have(slug):
    """True once the resized WebP files exist (made by photos/batch.py). Pages skip photos until then."""
    return all(os.path.exists(os.path.join(ROOT, "img", "%s-%d.webp" % (slug, w))) for w in (480, 960))

PHOTOS_LIST = [
    dict(slug='home-tiger-cub', used_on='index.html', alt='A sleepy tiger cub resting its chin on a rock among green leaves', title='Tired Tiger Cub (29323748176).jpg', page='https://commons.wikimedia.org/wiki/File:Tired_Tiger_Cub_(29323748176).jpg', author='Mathias Appel', lic='CC0', licurl='https://creativecommons.org/publicdomain/zero/1.0/deed.en', orig='https://upload.wikimedia.org/wikipedia/commons/d/d4/Tired_Tiger_Cub_%2829323748176%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', focus=0.5),
    dict(slug='lion', used_on='lion.html', alt='Close up of a male African lion with a thick golden mane', title='African Lion (40307117333).jpg', page='https://commons.wikimedia.org/wiki/File:African_Lion_(40307117333).jpg', author='Mathias Appel', lic='CC0', licurl='https://creativecommons.org/publicdomain/zero/1.0/deed.en', orig='https://upload.wikimedia.org/wikipedia/commons/9/91/African_Lion_%2840307117333%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', focus=0.5),
    dict(slug='tiger', used_on='tiger.html', alt='A wild Bengal tigress sitting on a sandy track in Pilibhit Tiger Reserve, India', title='A Bengal tigress (Panthera tigris tigris) in syphon area of Pilibhit tiger reserve.jpg', page='https://commons.wikimedia.org/wiki/File:A_Bengal_tigress_(Panthera_tigris_tigris)_in_syphon_area_of_Pilibhit_tiger_reserve.jpg', author='Pixel009', lic='CC0', licurl='https://creativecommons.org/publicdomain/zero/1.0/deed.en', orig='https://upload.wikimedia.org/wikipedia/commons/d/d4/A_Bengal_tigress_%28Panthera_tigris_tigris%29_in_syphon_area_of_Pilibhit_tiger_reserve.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', focus=0.5),
    dict(slug='leopard', used_on='leopard.html', alt='A leopard resting on the branches of a tree in Serengeti National Park, Tanzania', title='Leopard Serengeti.jpg', page='https://commons.wikimedia.org/wiki/File:Leopard_Serengeti.jpg', author='Naturedata', lic='CC0', licurl='https://creativecommons.org/publicdomain/zero/1.0/deed.en', orig='https://upload.wikimedia.org/wikipedia/commons/a/a6/Leopard_Serengeti.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', focus=0.5),
    dict(slug='jaguar', used_on='jaguar.html', alt='A jaguar walking through grass, showing large rosettes with dots inside', title='Panthera onca in Jardim Zoológico de Curitiba.jpg', page='https://commons.wikimedia.org/wiki/File:Panthera_onca_in_Jardim_Zool%C3%B3gico_de_Curitiba.jpg', author='Wilfredor', lic='CC0', licurl='https://creativecommons.org/publicdomain/zero/1.0/deed.en', orig='https://upload.wikimedia.org/wikipedia/commons/0/02/Panthera_onca_in_Jardim_Zool%C3%B3gico_de_Curitiba.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', focus=0.5),
    dict(slug='cheetah', used_on='cheetah.html', alt='A cheetah standing in long grass in the Maasai Mara, Kenya', title='Cheetah (Acinonyx jubatus), Maasai Mara.jpg', page='https://commons.wikimedia.org/wiki/File:Cheetah_(Acinonyx_jubatus),_Maasai_Mara.jpg', author='Hobbyfotowiki', lic='CC0', licurl='https://creativecommons.org/publicdomain/zero/1.0/deed.en', orig='https://upload.wikimedia.org/wikipedia/commons/a/af/Cheetah_%28Acinonyx_jubatus%29%2C_Maasai_Mara.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', focus=0.5),
    dict(slug='snow-leopard', used_on='snow-leopard.html', alt='A snow leopard with a thick pale grey spotted coat walking past green plants', title='Snow leopard at bronx zoo.jpg', page='https://commons.wikimedia.org/wiki/File:Snow_leopard_at_bronx_zoo.jpg', author='Ryan Schwark', lic='CC0', licurl='https://creativecommons.org/publicdomain/zero/1.0/deed.en', orig='https://upload.wikimedia.org/wikipedia/commons/0/02/Snow_leopard_at_bronx_zoo.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', focus=0.5),
    dict(slug='lion-yawn', used_on='blog/which-big-cats-can-roar.html', alt='A male lion with its mouth wide open in a big yawn, Kgalagadi', title='Panthera leo yawn (Kgalagadi, 2012).jpg', page='https://commons.wikimedia.org/wiki/File:Panthera_leo_yawn_(Kgalagadi,_2012).jpg', author='Yathin S Krishnappa', lic='CC BY-SA 3.0', licurl='https://creativecommons.org/licenses/by-sa/3.0', orig='https://upload.wikimedia.org/wikipedia/commons/e/ec/Panthera_leo_yawn_%28Kgalagadi%2C_2012%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', focus=0.5),
    dict(slug='leopard-road', used_on='blog/leopard-vs-jaguar-vs-cheetah.html', alt='A leopard on a dirt road looking back over its shoulder, showing its small rosettes', title='Panthera pardus (passant regardant).jpg', page='https://commons.wikimedia.org/wiki/File:Panthera_pardus_(passant_regardant).jpg', author='martynseddon (via Unsplash)', lic='CC0', licurl='https://creativecommons.org/publicdomain/zero/1.0/deed.en', orig='https://upload.wikimedia.org/wikipedia/commons/5/50/Panthera_pardus_%28passant_regardant%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', focus=0.5),
    dict(slug='cheetah-run', used_on='blog/how-fast-is-a-cheetah.html', alt='A cheetah at full sprint across short grass, legs stretched out', title='Gepardjagt1 (Acinonyx jubatus).jpg', page='https://commons.wikimedia.org/wiki/File:Gepardjagt1_(Acinonyx_jubatus).jpg', author='Malene Thyssen', lic='CC BY-SA 3.0', licurl='https://creativecommons.org/licenses/by-sa/3.0', orig='https://upload.wikimedia.org/wikipedia/commons/4/4c/Gepardjagt1_%28Acinonyx_jubatus%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', focus=0.5),
    dict(slug='tiger-fog', used_on='blog/why-do-tigers-have-stripes.html', alt='A wild Bengal tiger crossing a forest track on a misty morning, its stripes blending with the shadows', title='A Bengal tiger (Panthera tigris tigris) stretching on a foggy morning at Pilibhit tiger reserve.jpg', page='https://commons.wikimedia.org/wiki/File:A_Bengal_tiger_(Panthera_tigris_tigris)_stretching_on_a_foggy_morning_at_Pilibhit_tiger_reserve.jpg', author='Pixel009', lic='CC0', licurl='https://creativecommons.org/publicdomain/zero/1.0/deed.en', orig='https://upload.wikimedia.org/wikipedia/commons/2/2b/A_Bengal_tiger_%28Panthera_tigris_tigris%29_stretching_on_a_foggy_morning_at_Pilibhit_tiger_reserve.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', focus=0.62),
    dict(slug='tiger-cub-kanha', used_on='blog/how-many-big-cats-are-left.html', alt='A wild tigress and her cub nuzzling on a forest track in Kanha, India', title='Tiger with cub kanha.jpg', page='https://commons.wikimedia.org/wiki/File:Tiger_with_cub_kanha.jpg', author='Davidvraju', lic='CC0', licurl='https://creativecommons.org/publicdomain/zero/1.0/deed.en', orig='https://upload.wikimedia.org/wikipedia/commons/0/09/Tiger_with_cub_kanha.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', focus=0.5),
    dict(slug='lion-pride', used_on='blog/why-do-lions-live-in-prides.html', alt='Three lions of one pride resting together in the morning, Maasai Mara', title='Lions Family Portrait Masai Mara.jpg', page='https://commons.wikimedia.org/wiki/File:Lions_Family_Portrait_Masai_Mara.jpg', author='Benh LIEU SONG', lic='CC BY-SA 3.0', licurl='https://creativecommons.org/licenses/by-sa/3.0', orig='https://upload.wikimedia.org/wikipedia/commons/a/a1/Lions_Family_Portrait_Masai_Mara.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', focus=0.5),
    dict(slug='cheetah-grass', used_on='teachers/index.html', alt='A cheetah lying in golden grass in Serengeti National Park, Tanzania', title='Cheetah Serengeti 1.jpg', page='https://commons.wikimedia.org/wiki/File:Cheetah_Serengeti_1.jpg', author='Naturedata', lic='CC0', licurl='https://creativecommons.org/publicdomain/zero/1.0/deed.en', orig='https://upload.wikimedia.org/wikipedia/commons/b/bc/Cheetah_Serengeti_1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', focus=0.5),
]
PHOTOS = {p["used_on"]: p for p in PHOTOS_LIST}

def credit_line(p):
    lic = '<a href="%s" rel="license noopener">%s</a>' % (html.escape(p["licurl"]), p["lic"])
    return 'Photo: %s, %s, via <a href="%s" rel="noopener">Wikimedia Commons</a>' % (html.escape(p["author"]), lic, html.escape(p["page"]))

def photo_html(path, rel, lazy=True):
    p = PHOTOS[path]; s = rel + "img/" + p["slug"]
    if not have(p["slug"]):
        return ""
    load = ' loading="lazy"' if lazy else ' fetchpriority="high"'
    return ('<figure class="photo"><img src="%s-960.webp" srcset="%s-480.webp 480w, %s-960.webp 960w" sizes="(max-width: 1000px) 94vw, 940px" '
            'width="960" height="640" alt="%s"%s decoding="async"><figcaption>%s. %s.</figcaption></figure>') % (
            s, s, s, html.escape(p["alt"]), load, html.escape(p["alt"]), credit_line(p))
